[package]
name = "ckb-script"
version = "0.41.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"
description = "CKB component to run the type/lock scripts."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[features]
default = ["logging", "asm"]

asm = ["ckb-vm/asm"]
detect-asm = ["ckb-vm/detect-asm"]
logging = ["ckb-logger"]

[dependencies]
ckb-traits = { path = "../traits", version = "= 0.41.0-pre" }
byteorder = "1.3.1"
ckb-types = {path = "../util/types", version = "= 0.41.0-pre"}
ckb-hash = {path = "../util/hash", version = "= 0.41.0-pre"}
# TODO ckb2021 Remove git for ckb-vm* after new version of ckb-vm released.
ckb-vm-definitions = { version = "0.19", git = "https://github.com/yangby-cryptape/ckb-vm", rev = "d010e1c" }
ckb-vm = { version = "0.19", git = "https://github.com/yangby-cryptape/ckb-vm", rev = "d010e1c", default-features = false }
faster-hex = "0.4"
ckb-logger = { path = "../util/logger", version = "= 0.41.0-pre", optional = true }
serde = { version = "1.0", features = ["derive"] }
ckb-error = { path = "../error", version = "= 0.41.0-pre" }
ckb-chain-spec = { path = "../spec", version = "= 0.41.0-pre" }
goblin = "0.2"

[dev-dependencies]
proptest = "0.9"
ckb-db = { path = "../db", version = "= 0.41.0-pre" }
ckb-store = { path = "../store", version = "= 0.41.0-pre" }
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.41.0-pre" }
tiny-keccak = "2.0"
ckb-crypto = { path = "../util/crypto", version = "= 0.41.0-pre" }
ckb-db-schema = { path = "../db-schema", version = "= 0.41.0-pre" }
