name: AWS VM check
on:
  push:
    branches: ['usless_vm_check']
jobs:
  backport:
    runs-on: ubuntu-20.04
    name: AWS VM check
    steps:
      - name: AWS VM check
        run: |
          echo "AWS VM check"
      - name: Install AWS CLI 2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1
      - name: Configure AWS credentials
        run: aws ec2 help