name: CI
on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  CKB_CLI_VERSION: v0.40.0
    
jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


