name: CI
on: 
  push:
    branches: [ github_action_learn ]
  pull_request:
    branches: [ github_action_learn ]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  CKB_CLI_VERSION: v0.40.0
    
jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Test
      run: make test
    # strategy:
    #   matrix:
    #     allow_failures:
    #        - rust: stable
    #     include:
    #       - name: PR Integration
    #         run:
    #           script: make CKB_TEST_SEC_COEFFICIENT=5 CKB_TEST_ARGS="-c 4 --no-report" integration
    #       - name: Linters
    #         run:
    #           install:
    #             - cargo fmt --version || travis_retry rustup component add rustfmt
    #             - cargo clippy --version || travis_retry rustup component add clippy
    #           script:
    #             - make fmt
    #             - make clippy
    #             - git diff --exit-code Cargo.lock
    # - name: Build
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose


