name: ci_integration_test
concurrency:
  group: ci_integration_test-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - master
      - develop
      - trying
      - staging
      - 'rc/*'


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings
jobs:
  prologue:
    name: prologue
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: set-output
        id: set-matrix
        run: |
          runs_on=`${{github.workspace}}/devtools/ci/ci_prologue.sh`
          echo $runs_on
          echo "::set-output name=matrix::{\"os\":$runs_on}"
  ci_integration_test:
    name: ci_integration_test
    needs: prologue
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.prologue.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
    - if: ${{ runner.os == 'Windows' }}
      run: |
        iex (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "${{ github.workspace }}\devtools\windows" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        scoop install git
        scoop bucket add extras
        scoop install llvm yasm
    - run: |
        "${{ github.workspace }}/devtools/ci/ci_main.sh" ci_integration_test
      shell: bash
    - name: setup_python
      if: always()
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: ci_epilogue
      if: always()
      run: |
        pip install -r ${{ github.workspace }}/devtools/ci/requirements.txt
        python3 ${{ github.workspace }}/devtools/ci/ci_epilogue.py > result.log
        cat result.log
    - name: Post Run - Upload integration Result when failed
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: Integration Logs (${{ runner.os }}, ${{ matrix.os }})
        path: ${{ env.CKB_INTEGRATION_TEST_TMP }}/integration.log
    env:
      COMMIT_MESSAGE: ${{github.event.head_commit.message}}
      ACTOR: ${{github.actor}}
      CI_RUNS_ON: ${{secrets.CI_RUNS_ON}}
      REPO_OWNER: ${{github.repository_owner}}
      EVENT_NAME: ${{github.event_name}}
      REPOSITPRY: ${{ github.repository }}
      TOKEN: ${{secrets.WORKFLOW_TOKEN}}
      PR_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      PR_COMMONS_BODY: "${{ github.event.pull_request.body }}"
      COMMIT_SHA: ${{ github.sha }}
      workspace: ${{ github.workspace }}
      SENTRY_DSN: "https://15373165fbf2439b99ba46684dfbcb12@sentry.nervos.org/7"
      ImageOS: ${{matrix.os}}
      BUILD_BUILDID: ${{ github.run_id }}
      CKB_TEST_ARGS: -c 4 --no-report --no-fail-fast
