name: ci_quick_check
concurrency:
  group: ci_quick_check-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - master
      - develop
      - trying
      - staging
      - 'rc/*'


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings
jobs:
  ci_quick_check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: ci_quick_check
      run: |
        make check-cargotoml
        make check-whitespaces
        make check-dirty-rpc-doc
        make check-dirty-hashes-toml
        devtools/ci/check-cyclic-dependencies.py
    - name: ci_epilogue
      if: always()
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
        pip install -r ${{ github.workspace }}/devtools/ci/requirements.txt
        python3 ${{ github.workspace }}/devtools/ci/ci_epilogue.py > result.log
        cat result.log
    env:
      COMMIT_MESSAGE: ${{github.event.head_commit.message}}
      ACTOR: ${{github.actor}}
      CI_RUNS_ON: ${{secrets.CI_RUNS_ON}}
      REPO_OWNER: ${{github.repository_owner}}
      EVENT_NAME: ${{github.event_name}}
      REPOSITPRY: ${{ github.repository }}
      TOKEN: ${{secrets.WORKFLOW_TOKEN}}
      PR_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      COMMIT_SHA: ${{ github.sha }}
      workspace: ${{ github.workspace }}
