name: Cron job for master&&develop branch

on:
  schedule:
    - cron: '0 23 * * *'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  CARGO_TARGET_DIR: ${{ github.workspace }}/../target
  LOGBAK_USER: ${{secrets.LOGBAK_USER}}  #LOCBAK_* for upload logs to server when test failed, for windows
  LOGBAK_PASSWORD: ${{secrets.LOGBAK_PASSWORD}}
  LOGBAK_SERVER: ${{secrets.LOGBAK_SERVER}}
jobs:
  UnitTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux, macOS,Windows]
        include:
          - os: Linux
            script_run: make test
          - os:  macOS
            script_run: make test
          - os: Windows
            script_run: devtools/windows/make test
            CI: true
        branch:
          - master
          - develop
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    - name: UnitTest
      run: ${{ matrix.script_run }}
    env:
      CI: ${{ matrix.CI }}

  Benchmarks_Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux, macOS]
        branch:
          - master
          - develop
    needs: UnitTest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    - name: Benchmarks_Test
      run: make bench-test

  Integration_Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux, macOS,Windows]
        include:
          - os: Linux
            script_run: make integration
          - os:  macOS
            script_run: make integration
          - os: Windows
            script_run: devtools/windows/make CKB_TEST_SEC_COEFFICIENT=5 CKB_TEST_ARGS="-c 4 --no-report" integration
            CI: true
            SENTRY_DSN: "https://15373165fbf2439b99ba46684dfbcb12@sentry.nervos.org/7"
        branch:
          - master
          - develop
    needs: Benchmarks_Test
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    - name: Integration_Test
      run: ${{ matrix.script_run }}
    env:
      CI: ${{ matrix.CI }}
      SENTRY_DSN: ${{ matrix.SENTRY_DSN }}
      ACTIONS_ID: ${{github.run_id}}
      ACTIONS_OS_NAME: ${{matrix.os}}
      BUILD_BUILDID: ${{ github.run_id }}

  Linters:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux, macOS]
    needs: Integration_Test
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Linters
      run: |
         cargo fmt --version || rustup component add rustfmt
         cargo clippy --version || rustup component add clippy
         make fmt
         make clippy
         git diff --exit-code Cargo.lock

  Latest_Linters:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux, macOS]
        include:
          - os: Linux-runner
            script_run: rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu &&  rustup component add clippy --toolchain stable-x86_64-unknown-linux-gnu
          - os:  mac-runner
            script_run: rustup component add rustfmt-preview && rustup component add clippy-preview
    needs: Linters
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Pre install
      run: ${{ matrix.script_run }}
    - name: Latest_Linters
      run: |
        mv rust-toolchain rust-toolchain.bak
        echo "stable" > rust-toolchain
        make fmt
        make clippy
        mv rust-toolchain.bak rust-toolchain

  Quick_Check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux, macOS]
    needs: Latest_Linters
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Quick_Check
      run: |
        make check-cargotoml
        make check-whitespaces
        make check-dirty-rpc-doc
        make check-dirty-hashes-toml
        devtools/ci/check-cyclic-dependencies.py

  Cyclic_dev_dependencies:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux, macOS]
    needs: Quick_Check
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Cyclic_dev_dependencies
      run: |
        devtools/ci/check-cyclic-dependencies.py --dev

  Security_Audit_Licenses:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux, macOS]
    needs: Cyclic_dev_dependencies
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Security Audit & Licenses
      run: |
        cargo deny --version || travis_retry cargo install cargo-deny --locked
        make security-audit
        make check-crates
        make check-licenses

  WASM_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux, macOS]
    needs: Security_Audit_Licenses
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: WASM build
      run: |
        export PATH=/usr/lib/llvm-8/bin:$PATH
        rustup target add wasm32-unknown-unknown
        make wasm-build-test

  Code_Coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux]
    needs: WASM_build
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Code Coverage
      run: |
        cargo tarpaulin --version || travis_retry cargo install cargo-tarpaulin --locked
        if make cov; then bash <(curl -s https://codecov.io/bash); fi
      env:
        CACHE_NAME: tarpaulin