name: Integration test

on:
  pull_request_review:
    types: [ submitted ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  CARGO_TARGET_DIR: ${{ github.workspace }}/../target
  LOGBAK_USER: ${{secrets.LOGBAK_USER}}  #LOCBAK_* for upload logs to server when test failed, for windows
  LOGBAK_PASSWORD: ${{secrets.LOGBAK_PASSWORD}}
  LOGBAK_SERVER: ${{secrets.LOGBAK_SERVER}}
jobs:
  Integration_Test:
    runs-on: ${{ matrix.os }}
    if: |
      contains(github.event.review.body, '#integration-test') &&
      contains(fromJson('[ "janx", "doitian", "quake", "xxuejie", "zhangsoledad", "jjyr", "TheWaWaR", "driftluo", "keroro520", "yangby-cryptape", "liya2017" ]'), github.actor)
    strategy:
      matrix:
        os: [Linux-runner, mac-runner,win-runner]
        include:
          - os: Linux-runner
            script_run: make integration
          - os:  mac-runner
            script_run: make integration
          - os: win-runner
            script_run: devtools/windows/make CKB_TEST_SEC_COEFFICIENT=5 CKB_TEST_ARGS="-c 4 --no-report" integration
            CI: true
            SENTRY_DSN: "https://15373165fbf2439b99ba46684dfbcb12@sentry.nervos.org/7"
    steps:
    - uses: actions/checkout@v2
    - name: Integration_Test
      run: ${{ matrix.script_run }}
    env:
      CI: ${{ matrix.CI }}
      SENTRY_DSN: ${{ matrix.SENTRY_DSN }}