name: Slash Command

on:
  issue_comment:
    types: [ created ]

jobs:

  slash-command:
    name: Trigger Execute Command
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: pull_request_payload
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
      - uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          commands: execute
          issue-type: pull-request
          static-args: |
            github_sha=${{ toJSON(fromJson(steps.pull_request_payload.outputs.result).data.head.sha) }}
