name: CI workflow

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  CARGO_TARGET_DIR: ${{ github.workspace }}/../target
  LOGBAK_USER: ${{secrets.LOGBAK_USER}}  #LOCBAK_* for upload logs to server when test failed, for windows
  LOGBAK_PASSWORD: ${{secrets.LOGBAK_PASSWORD}}
  LOGBAK_SERVER: ${{secrets.LOGBAK_SERVER}}
jobs:
  Integration_Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux-runner, mac-runner]
        include:
          - os: Linux-runner
            script_run: make CKB_TEST_SEC_COEFFICIENT=5 CKB_TEST_ARGS="-c 4 --no-report" integration
          - os:  mac-runner
            script_run: make CKB_TEST_SEC_COEFFICIENT=5 CKB_TEST_ARGS="-c 4 --no-report" integration
          # - os: win-runner
          #   script_run: devtools/windows/make CKB_TEST_SEC_COEFFICIENT=5 CKB_TEST_ARGS="-c 4 --no-report" integration
          #   SENTRY_DSN: "https://15373165fbf2439b99ba46684dfbcb12@sentry.nervos.org/7"
    steps:
    - uses: actions/checkout@v2
    - name: Integration_Test
      run: |
        ${{ matrix.script_run }}
    - name: Post Run - Upload integration Result when failed
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}_integration.log
        path: ${{ env.CKB_INTEGRATION_TEST_TMP }}/integration.log
    env:
      CI: true
      SENTRY_DSN: ${{ matrix.SENTRY_DSN }}
      ACTIONS_OS_NAME: ${{matrix.os}}
      BUILD_BUILDID: ${{ github.run_id }}
