name: test job allow faliure

on:
  push:

jobs:
  Exit-1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Exit as 1
      run: exit 1

  test:
    if: always()
    runs-on: ubuntu-latest
    needs: Exit-1
    steps:
    - name: test
      run: echo "Test pr status"

  # Integration_Test:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [Linux,macOS]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Integration_Test
  #     run: make CKB_TEST_SEC_COEFFICIENT=5 CKB_TEST_ARGS="-c 4 --no-report" integration
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Set tag
        run: |
          export GIT_TAG_NAME=v0.38.2
          echo "GIT_TAG_NAME=$GIT_TAG_NAME" >> $GITHUB_ENV
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: "configs/configuration_repo.json"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.GIT_TAG_NAME}}
          release_name: ${{ env.GIT_TAG_NAME}}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: true
          prerelease: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
